# Generated by Django 3.1.7 on 2021-03-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_slug',
            field=models.SlugField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
